version: "3.8"
services:

  db:
    image: mysql
    container_name: td_db_mysql
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TIMEZONE: 'Europe/Paris'
    networks:
      - dev
    # command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin
    container_name: td_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: td_maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - dev

  www:
    build: php
    container_name: td_www
    ports:
      - "8000:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: unless-stopped
    networks:
      - dev
    environment:
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9000
      - PHP_IDE_CONFIG=serverName=acseo-docker

networks:
  dev:

volumes:
  db-data:

